LOGGER_FILE_PATH=./log.txt LOGGER_STDOUT=true LOGGER_LEVEL=debug go test ./logger/... 
GO_CRYPTO_SALT1=kKi?9 GO_CRYPTO_SALT2=password go test ./encryption/... 
go test ./uniquegenerator/...
go test ./validation/... 